# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93867a0f5270a40a6eaaf83cda3299933cd1e5da11c751115fd4541f272df60a0b66797abbe6f18eeed270302d3d3838c20138fdcfb2eb85405ceb49c7da299b

test:
  secret_key_base: adf84ddf844c2d8b56314efb9f5bdba0df676698da987602ea2fa1be8fa56e635d8b79dd9ab7dae2b6e4b005e2b61e4d7d85888db3db49b0e603dd0e413b7ded

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
